name: allcal
description: "All in One Calendar"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' # Flutter 버전에 따라 조정될 수 있습니다.

dependencies:
  flutter:
    sdk: flutter
  month_picker_dialog: ^2.6.0 # 년/월 선택을 위한 패키지
  # ... 다른 패키지들 ...
  
  # 캘린더 UI를 위한 필수 라이브러리
  table_calendar: ^3.0.9
  
  # 상태 관리를 위한 라이브러리 (Provider)
  provider: ^6.1.1
  
  # 날짜 포맷팅을 위한 라이브러리
  intl: ^0.18.1
  
  # 아이콘 사용을 위한 라이브러리
  cupertino_icons: ^1.0.2

  flutter_colorpicker: ^1.0.3 # 색상 선택(Color Picker) UI를 위한 패키지
  uuid: ^4.3.3              # 고유 ID 생성을 위한 패키지

  material_symbols_icons: ^4.2858.1 # pub.dev에서 최신 버전을 확인하세요

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true